### ISSUE TITLE
Uncompressing genome.fa.gz files prior to building custom Cell Ranger reference 

### ISSUE THREAD

**Issue by jarchana09** [mhammell-laboratory/CellRangerTE#1]
Hi Oliver and team,

Thank you very much for developing the immensely helpful TETranscripts tool, and the scRNA-seq wrapper CellRangerTE .

As CellRanger mkref requires an uncompressed fastq file, request you to kindly consider whether this could be amended to the bash script, if appropriate, specifically above the line of code included below:

https://github.com/mhammell-laboratory/CellRangerTE/blob/6fcd983d51e8c6be0579310565a4367f67e5405e/CellRanger-TE_database_generation.sh#L115-L116

Perhaps,
```
gunzip "${GENOME}.primary_assembly.genome.fa.gz"
FASTA="${GENOME}.primary_assembly.genome.fa"
```

Thank you so much.

Sincerely,
Archana

**Comment by olivertam** [comment]
Hi Archana,

Thank you for pointing out the issue. It has been fixed in this commit as suggested (7140ee3).

Thanks.
